import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/components/navs/Nav";
import Footer from "./ui/components/sections/Footer";
import { AuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='h-screen flex flex-col '>
        <div className="flex-1">
          <AuthProvider>
            <Nav/>
            {children}
          </AuthProvider>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
